config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "appointments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  before_save :set_summary

  validate :overlap
  validate :check_start_before_end

  private

  def set_summary
    # Meeting with Team - March 3rd, 2024, 10:00 AM to 11:00 AM
    month_section = "#{start_date.strftime("%B")} #{start_date.day.ordinalize}"
    year_section = "#{start_date.strftime("%Y")}"
    time_section = "#{start_date.strftime("%H:%M %p")} to #{end_date.strftime("%H:%M %p")}"
    summary = "#{title} - #{month_section}, #{year_section}, #{time_section}"
    self.summary = summary
  end

  def check_start_before_end
    errors.add(:start_date, 'must be before end date') if start_date > end_date
  end

  def overlap
    overlapping_appointments = Appointment.where.not(id: id).where('start_date < ? AND end_date > ?', end_date, start_date)

    if overlapping_appointments.exists?
      errors.add(:base, "The appointments overlaps with: #{overlapping_appointments.pluck(:title).join(", ")}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments or /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    @appointment.destroy!

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:title, :description, :start_date, :end_date, :summary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def beatiful_title_summary
    "* Summary *"
  end
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Title:</strong>
    <%= appointment.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= appointment.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= appointment.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= appointment.end_date %>
  </p>

  <p>
    <strong>Summary:</strong>
    <%= appointment.summary %>
  </p>

</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.datetime_field :end_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Show this appointment", @appointment %> |
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointments</h1>

<div id="appointments">
  <table>
    <tr>
      <th><%= beatiful_title_summary %></th>
      <th colspan="2">Actions</th>
    </tr>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.summary %></td>
        <td><%= link_to "Show", appointment %></td>
        <td><%= link_to "Edit", edit_appointment_path(appointment) %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "New appointment", new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render "form", appointment: @appointment %>

<br>

<div>
  <%= link_to "Back to appointments", appointments_path %>
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppointmentScheduler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>